# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Seed Categories
categories = [
  { name: 'Knitting & Crochet' },
  { name: 'Sewing' },
  { name: 'DIY Kits' },
  { name: 'Painting' },
  { name: 'Kids' },
  { name: 'Cross Stitch' },
]
Category.create(categories)

# Seed Customers
customers = [
  { first_name: 'Alice', last_name: 'White', email: 'alice.white@example.com', street_address: '123 Oak St', city: 'Toronto', province: 'ON', postal_code: 'M5V 1J9' },
  { first_name: 'David', last_name: 'Hill', email: 'david.hill@example.com', street_address: '456 Maple St', city: 'Vancouver', province: 'BC', postal_code: 'V6B 2P4' },
  { first_name: 'Sophia', last_name: 'Mitchell', email: 'sophia.mitchell@example.com', street_address: '789 Pine St', city: 'Montreal', province: 'QC', postal_code: 'H2X 1L4' },
  { first_name: 'Liam', last_name: 'Wilson', email: 'liam.wilson@example.com', street_address: '101 Elm St', city: 'Calgary', province: 'AB', postal_code: 'T2P 3Y6' },
  { first_name: 'Ella', last_name: 'Anderson', email: 'ella.anderson@example.com', street_address: '202 Cedar St', city: 'Ottawa', province: 'ON', postal_code: 'K1N 9B4' },
  { first_name: 'Mason', last_name: 'Cooper', email: 'mason.cooper@example.com', street_address: '303 Maple St', city: 'Edmonton', province: 'AB', postal_code: 'T5J 0J8' },
  { first_name: 'Ava', last_name: 'Bailey', email: 'ava.bailey@example.com', street_address: '404 Birch St', city: 'Quebec City', province: 'QC', postal_code: 'G1S 4S3' },
  { first_name: 'Logan', last_name: 'Smith', email: 'logan.smith@example.com', street_address: '505 Pine St', city: 'Winnipeg', province: 'MB', postal_code: 'R3C 0V8' },
]
Customer.create(customers)

# Seed Products
products = [
  { name: 'Acrylic Yarn 3 Pack', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397543/knitting-starter-pack-product_hpsdzs.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397562/knitting-starter-pack-thumbnail_ez1lol.webp', description: 'Craft with sophistication using our 3-pack of acrylic yarn in charcoal, ivory, and dove grey. Ideal for knitting or crocheting, this premium yarn blend ensures your projects are not only visually stunning but also luxuriously soft. Elevate your creations with ease, adding a touch of modern elegance to scarves, blankets, and more. Enjoy the perfect blend of style and comfort with our exquisite acrylic yarn set.', price: 16.99, inventory: 12 },
  { name: 'Retro Styled Sewing Machine', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397558/sewing-retro-machine-product_qowvw1.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397554/sewing-retro-machine-thumbnail_umvdhk.webp', description: 'Introducing our Retro-Inspired Sewing Machine, a perfect blend of vintage charm and modern functionality. Embrace the nostalgia of yesteryear with its retro design, while enjoying the convenience of state-of-the-art sewing technology. This stylish machine effortlessly combines timeless aesthetics with cutting-edge features, making it a must-have for both vintage enthusiasts and contemporary crafters alike. Sew with flair, embracing the best of both worlds with our Retro-Inspired Sewing Machine.', price: 249.99, inventory: 32 },
  { name: 'Knitting Starter Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397550/knitting-starter-pack2-product_bry0w8.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397547/knitting-starter-pack2-thumbnail_i3hn3e.webp', description: 'Embark on a cozy crafting journey with our Knitting Starter Kit, a delightful ensemble designed for beginners. This kit features luxurious grey and brown yarn, accompanied by a set of ergonomic needles and all the essential supplies to ignite your passion for knitting. Unleash your creativity and dive into the world of handmade warmth with this comprehensive and stylish starter kit.', price: 49.99, inventory: 6 },
  { name: 'Cross Stitch Thread Variety Pack', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397263/crossstich-thread-kit-sm-product_scqf9u.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397259/crossstich-thread-kit-sm-thumbnail_byqnpn.webp', description: 'Indulge your cross-stitching dreams with our Cross Stitch Thread Variety Pack, a vibrant collection of 12 of the most popular and enchanting colors. Unleash your creativity as you weave a tapestry of hues, each thread meticulously chosen to elevate your stitching projects. Whether you are a seasoned crafter or just starting, this multi-pack is a colorful essential for bringing your needlework visions to life.', price: 9.99, inventory: 16 },
  { name: 'Stylish Yarn Basket', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706456956/knitting-yarn-with-basket-product_szd2ck.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397266/knitting-yarn-with-basket-thumbnail_kizxaw.webp', description: 'Elevate your crafting space with our Chic Yarn Storage Basket, a stylish and practical addition to any creative corner. This delightful basket not only serves as a sophisticated yarn storage solution but also comes with six exquisite shades of grey and white yarns. Organize your threads with flair, and let this elegant basket be both a functional and aesthetic centerpiece for your crafting haven.', price: 36.99, inventory: 5 },
  { name: 'Watercolor Paint Set', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387152/painting-watercolor-tray-product_upifx7.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387151/painting-watercolor-tray-thumbnail_pfjc73.webp', description: 'Ignite your artistic imagination with our Watercolor Paint Set, a palette of 15 dazzling and vibrant hues. Perfect for both budding artists and seasoned creators, this set offers a spectrum of brilliant colors to bring your visions to life. Dive into a world of creativity, where every stroke is infused with the richness of these watercolors, ensuring your artwork bursts with vivid brilliance.', price: 14.99, inventory: 15 },
  { name: 'Kids Felt Craft Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397255/kids-craft-kit-product_mbg39y.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706397252/kids-craft-kit-thumbnail_algjj2.webp', description: 'Inspire little ones to dream big with our Kids Felt Craft Kit, a delightful and easy-to-assemble project that results in a charming pastel banner adorned with a whimsical rainbow. This kit sparks creativity in children, providing a fun crafting experience as they create their very own decorative masterpiece.', price: 14.99, inventory: 25 },
  { name: 'Metal Pail Paintbrush Storage', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706396894/paint-supply-organizer-product_sqvs8y.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706396890/paint-supply-organizer-thumbnail_mxwnte.webp', description: 'Revolutionize your crafting space with our Modern Metal Pail Paint Supply Storage Solution, an innovative and chic way to keep your brushes, stir sticks, and pencils organized. This unique design features an array of metal pails in various sizes, elegantly attached to create a functional and stylish storage unit. Elevate your creative haven with this contemporary solution, ensuring your tools are not only within reach but also showcased in a sophisticated arrangement.', price: 44.99, inventory: 28 },
  { name: 'Rainbow Thread & Bobbin Set', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706396887/sewing-multi-thread-bobbin-pack-product_zkw4kh.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706396883/sewing-multi-thread-bobbin-pack-thumbnail_ihxqv9.webp', description: 'Dive into a world of vibrant stitching possibilities with our Rainbow Thread and Metal Bobbin Multi-Pack, a kaleidoscopic assortment that adds a burst of color to your sewing projects. This pack features a spectrum of hues across various threads neatly wound on metal bobbins, offering both organization and creative inspiration.', price: 16.99, inventory: 4 },
  { name: 'Christmas Wreath Making Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706396868/diy-christmas-wreath-product_qoavk5.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706396864/diy-christmas-wreath-thumbnail_nwnduk.webp', description: 'Create lasting holiday memories with our Christmas Wreath Making Kit, a blend of tradition and rustic charm in one delightful package. Crafted with timeless elegance, this kit includes all the materials needed to fashion a beautiful wreath that will grace your home for years to come. Embrace the joy of DIY decorating and infuse your space with the warmth and enduring beauty of this classic Christmas accessory.', price: 56.99, inventory: 14 },
  { name: 'Bobbin 6 Pack', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706396861/sewing-bobbin-6pack-product_bg1yd3.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706396858/sewing-bobbin-6pack-thumbnail_ckdagd.webp', description: 'Upgrade your sewing experience with our Metal Bobbin 6-Pack, a convenient set pre-loaded with an assortment of captivating blue threads. Designed for both efficiency and style, these metal bobbins ensure seamless stitching and add a touch of color variety to your sewing projects.', price: 6.99, inventory: 0 },
  { name: 'Crochet Hook Multi Pack', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706394693/knitting-crochet-needles-product_ufgl8f.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706394690/knitting-crochet-needles-thumbnail_hyfurr.webp', description: 'Unleash your creativity with our Pink Crochet Hook Multi-Pack, a vibrant collection featuring various sizes of hooks in a playful and feminine pink color scheme. Perfect for both beginners and seasoned crafters, this set offers versatility and flair to elevate your crochet projects.', price: 22.99, inventory: 10 },
  { name: 'Painting Starter Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706394687/painting-starter-kit-product_o2tbse.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706394683/painting-starter-kit-thumbnail_h1gs6r.webp', description: 'Embark on your artistic journey with our Painting Starter Kit, a comprehensive set that provides everything you need to dive into the world of painting. This kit includes a diverse array of paints and brushes, accompanied by a sketchbook, pencils, and convenient storage trays for effortless organization. Whether you are a budding artist or looking to expand your creative horizons, this all-in-one kit ensures a seamless and enjoyable start to your painting hobby.', price: 52.99, inventory: 8 },
  { name: 'Kids Rock Painting Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706393095/kids-rock-painting-product_z37vxi.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706393091/kids-rock-painting-thumbnail_xjkjhq.webp', description: 'Ignite the imagination of your child with our Rock Painting Kit, a delightful set that transforms ordinary rocks into works of art. This kit includes an assortment of brushes, vibrant paints, and two starter rocks, providing everything needed for endless creative exploration. Watch as your little artist brings these rocks to life, turning them into charming masterpieces that add a touch of whimsy to any space.', price: 18.99, inventory: 8 },
  { name: 'Uplifting Embroidery Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706392750/diy-embroidery-kit-product_koqtuw.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706392772/diy-embroidery-kit-thumbnail_fdxty8.webp', description: 'Spread joy and creativity with our Uplifting Embroidery Kit, a delightful package that encapsulates the theme of happiness in three charming projects. Packed with all the necessary supplies, including vibrant threads, needles, and uplifting patterns, this kit is perfect for both beginners and seasoned crafters. Unleash your artistic spirit and stitch your way to positivity with these heartwarming and cheerful embroidery projects.', price: 28.99, inventory: 38 },
  { name: 'Kids Starter Paint Set', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706392769/kids-starter-paint-set-product_kkrojx.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706392765/kids-starter-paint-set-thumbnail_i790ew.webp', description: 'Introduce your little ones to the world of art with our Kids Starter Paint Kit, a creative wonderland that includes an array of brushes, a compact sketchbook, and a vibrant paint palette. This all-in-one kit provides budding artists with everything they need to explore their imagination and bring their colorful visions to life.', price: 18.99, inventory: 8 },
  { name: 'Kids Easter Craft Set', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706392762/kids-easter-craft-kit-product_gk2l8m.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706392759/kids-easter-craft-kit-thumbnail_nskbhd.webp', description: 'Celebrate the joy of Easter with our Kids Easter Craft Set, a delightful package brimming with creative fun for little ones. Packed with an assortment of festive materials, this set invites children to embark on a crafting adventure, making their own colorful Easter-themed creations.', price: 14.99, inventory: 26 },
  { name: 'All In One Wooden Easel', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706392756/painting-easel2-product_raa2h8.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706392753/painting-easel2-thumbnail_c0ftx2.webp', description: 'Elevate your artistic experience with our High-Quality Adjustable Wooden Easel, a versatile and sturdy companion for creators of all levels. Crafted with precision and durability, this easel boasts full adjustability to accommodate various canvas sizes. The thoughtful addition of a small ledge ensures convenient access to paints and brushes, making it the perfect companion for unleashing your creativity with ease and sophistication.', price: 114.99, inventory: 6 },
  { name: 'Scrapbooking Starter Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390575/diy-scrapbooking-starter-product_smearr.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390587/diy-scrapbooking-starter-thumbnail_mbu0yc.webp', description: 'Embark on a journey of cherished memories with our Scrapbooking Starter Kit, a comprehensive set designed to ignite your creativity in preserving every special moment. This kit includes an assortment of high-quality papers, decorative elements, and essential tools, providing everything you need to begin crafting beautiful scrapbook pages.', price: 54.99, inventory: 23 },
  { name: 'Kids Clay Modelling Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390584/kids-clay-model-kit-product_u3o9on.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390548/kids-clay-model-kit-thumbnail_afjips.webp', description: 'Unleash imaginations with our Kids Clay Modeling Kit, a delightful set that brings their creative visions to life. Packed with vibrant, non-toxic clay in an array of colors and easy-to-use sculpting tools, this kit is perfect for little hands eager to craft their own masterpieces. Watch as your young artist explores the joy of sculpting and creates whimsical figures with this engaging and mess-free clay modeling experience', price: 19.99, inventory: 2 },
  { name: 'Elegant Paper Flower Making Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390581/diy-paper-flower-kit-product_lzu80c.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390578/diy-paper-flower-kit-thumbnail_konrnh.webp', description: 'Indulge in the art of floral craftsmanship with our Elegant Paper Flower Making Kit, a sophisticated ensemble designed to bring the beauty of blooms to your fingertips. This kit includes premium-quality paper in exquisite shades, along with easy-to-follow instructions and essential crafting tools. Elevate your space with handcrafted elegance as you immerse yourself in the meditative and rewarding process of creating everlasting paper flowers that capture the essence of nature.', price: 49.99, inventory: 0 },
  { name: 'Kids Sticker Crafting Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390545/kids-sticker-making-kit-product_zvkctl.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390557/kids-sticker-making-kit-thumbnail_fgxmrq.webp', description: 'Ignite their creativity with our Kids Sticker Crafting Kit, a delightful set that transforms imagination into tangible, three-dimensional stickers. This kit provides everything young crafters need to design and craft their own puffy stickers, including colorful sheets, markers, and fun shapes.', price: 18.99, inventory: 10 },
  { name: 'Felt Bears Sewing Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390554/kids-stuffies-sewing-kit-product_z9vgsu.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706390551/kids-stuffies-sewing-kit-thumbnail_p1xzgm.webp', description: 'Embark on a heartwarming crafting adventure with our Felt Bears Sewing Kit, a delightful package that provides all the materials needed to create two irresistibly soft stuffed bears. This kit is perfect for both beginners and seasoned crafters, offering pre-cut felt pieces, step-by-step instructions, and stuffing to bring these adorable bears to life. Immerse yourself in the joy of crafting and embrace the cuddly companionship of these hand-sewn treasures.', price: 32.99, inventory: 18 },
  { name: 'Shawl Knitting Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389675/knitting-shawl-kit-product_zviz4m.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389695/knitting-shawl-kit-thumbnail_i1raql.webp', description: 'Experience the artistry of knitting with our Shawl Knitting Kit, a sophisticated offering designed for those seeking a captivating challenge. This kit features an exquisite and intricate pattern, making it ideal for experienced crafters looking to elevate their knitting skills. Create a timeless and elegant shawl that reflects the beauty of expert craftsmanship, showcasing the joy of knitting at an advanced level.', price: 22.99, inventory: 38 },
  { name: 'Beginner Cross Stitch Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389692/crossstitch-small-heart-product_qenxnp.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389689/crossstitch-small-heart-thumbnail_csrxld.webp', description: 'Embark on your cross-stitching journey with our Beginner Cross Stitch Kit, a delightful project that introduces newcomers to the timeless art of needlecraft. This kit includes all the essentials to create a charming small piece featuring a radiant red heart, making it the perfect starting point for those new to cross stitching. Dive into the world of stitching with ease and create a beautiful keepsake that captures the simplicity and joy of this beloved craft.', price: 12.99, inventory: 30 },
  { name: 'Knitting Accessory Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389687/knitting-accessory-kit-product_tvqx3o.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389684/knitting-accessory-kit-thumbnail_xffbah.webp', description: 'Elevate your knitting experience or surprise a budding enthusiast with our Knitting Accessory Kit, a versatile collection perfect for both beginners and seasoned crafters. This thoughtfully curated set includes essential accessories such as stitch markers, needle gauges, and cable needles – ideal for those just starting out or seasoned knitters looking to refresh their toolkit. Enhance the joy of knitting and make every stitch a delight with this comprehensive and stylish accessory kit', price: 22.99, inventory: 21 },
  { name: 'Lambswool 4 Pack', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389681/knitting-lambs-wool-pack-product_ucdzg3.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389678/knitting-lambs-wool-pack-thumbnail_gcmuyh.webp', description: 'Indulge in the luxury of our Lambswool 4-Pack, a premium selection featuring the highest quality fibers in classic black, white, and two elegant shades of grey. Perfect for creating premium handcrafted items, this exquisite wool blend promises unparalleled softness and warmth. Elevate your creations with the timeless appeal of these sophisticated shades, ensuring a touch of opulence in every knit and crochet project.', price: 52.99, inventory: 24 },
  { name: 'Floral Cross Stitch Pattern', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389658/crossstitch-flower-project-product_jamipz.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389655/crossstitch-flower-project-thumbnail_e9ojwb.webp', description: 'Infuse your stitching projects with a burst of joy using our Floral Cross Stitch Pattern. This vibrant design, adorned with bright and cheerful colors, brings a touch of sunshine to your needlework. Whether you are a seasoned cross-stitch enthusiast or a newcomer, this pattern adds a delightful and uplifting flair to your creative endeavors.', price: 7.99, inventory: 14 },
  { name: 'Kids Paper Mache Bird Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389652/kids-paper-mache-product_yr6isp.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389649/kids-paper-mache-thumbnail_ywubqk.webp', description: 'Unleash the creativity in a young mind with our Kids Paper Mache Bird Kit, a whimsical crafting adventure that brings a cute blue bird to life. Perfect for little hands, this kit includes all the materials needed for a delightful paper mache project. Whether used as an adorable decoration or transformed into a playful pinata, this kit promises hours of imaginative fun for aspiring young artists.', price: 17.99, inventory: 4 },
  { name: 'Serene Garden Cross Stitch Pattern', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389646/crossstitch-bird-flowers-product_ej4mhf.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706389644/crossstitch-bird-flowers-thumbnail_zhn5gt.webp', description: 'Escape into tranquility with our Serene Garden Cross Stitch Pattern, an enchanting design that captures the beauty of nature in muted color tones. This delicate scene features blooming flowers and a charming bird, creating a calming ambiance for your stitching endeavors. Immerse yourself in the therapeutic art of cross stitch as you bring this peaceful garden to life, stitch by stitch.', price: 11.99, inventory: 34 },
  { name: 'Vibrant Multicolor Yarn', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388625/knitting-rainbow-wool-product_mgzumw.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388639/knitting-rainbow-wool-thumbnail_a4yrtp.webp', description: 'Add a splash of color to your crafting palette with our Vibrant Multi-Color Yarn. This playful and bright yarn is perfect for adding a pop of energy to your knitting or crocheting projects. Let your creativity shine as you weave a spectrum of joyful hues into your next handmade creation.', price: 7.99, inventory: 24 },
  { name: 'Ballerina Bunnies Kids Crochet Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388636/kids-ballerina-bunnies-product_i1kkaw.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388633/kids-ballerina-bunnies-thumbnail_itfeff.webp', description: 'Introduce your older kids to the enchanting world of crochet with our Ballerina Bunnies Kids Crochet Kit. This delightful kit is designed for budding crafters eager to learn the art of crochet, allowing them to create a charming set of four ballerina bunnies. With step-by-step instructions and all the necessary materials included, this kit ensures a fun and rewarding experience as young hands bring these adorable dancers to life.', price: 29.99, inventory: 27 },
  { name: 'Crochet Hook Set', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388631/knitting-crochet-needle-case-product_m3lbqy.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388628/knitting-crochet-needle-case-thumbnail_ygubtg.webp', description: 'Upgrade your crochet experience with our Crochet Hook Set, a versatile ensemble featuring 8 hooks of varying sizes housed in a durable zip-up case. This comprehensive set is perfect for crafters of all levels, providing the tools you need to tackle various projects. Stay organized and crochet on-the-go with ease, thanks to the convenient and stylish case included in this must-have crochet hook set.', price: 19.99, inventory: 7 },
  { name: 'Pink Chunky Yarn', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388598/knitting-chunky-yarn-product_fkp2ly.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706482570/knitting-chunky-yarn-thumbnail_joedin.webp', description: 'Wrap yourself in warmth and luxury with our Pink Chunky Yarn, a delightfully soft and plush option perfect for crafting cozy sweaters or snuggly baby blankets. This premium yarn boasts a beautiful shade of pink, adding a touch of sweetness to your handmade creations. Elevate your knit or crochet projects with the sumptuous feel and vibrant color of this chunky yarn, ensuring both comfort and style in every stitch.', price: 9.99, inventory: 17 },
  { name: 'Baby Booties Knitting Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388593/knitting-baby-boots-kit-product_z9dssa.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388590/knitting-baby-boots-kit-thumbnail_fwqqy8.webp', description: 'Craft adorable and cozy baby booties with our Grey Knitting Kit, a complete package that includes all the yarn required for this delightful project. Perfect for both beginners and experienced knitters, this kit offers a charming shade of grey that adds a touch of sophistication to the cute little booties. Create a handmade keepsake for little ones or gift a cherished pair with this all-in-one knitting kit.', price: 39.99, inventory: 19 },
  { name: 'Premium Fall Tones Wool', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388588/knitting-premium-fall-yarn-product_ddgbez.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706388585/knitting-premium-fall-yarn-thumbnail_pm4j8z.webp', description: 'Indulge in the rich and warm hues of autumn with our Premium Fall Tones Wool Yarn. This exquisite yarn collection features a palette inspired by the changing seasons, offering a blend of deep oranges, rustic browns, and golden yellows. Elevate your fall-inspired projects with the luxurious feel and stunning colors of this premium wool yarn, perfect for creating cozy scarves, hats, and blankets that capture the essence of the season.', price: 19.99, inventory: 15 },
  { name: 'Professional Quality Sewing Machine', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387561/sewing-premium-machine-product_cb5nn1.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387554/sewing-premium-machine-thumbnail_yvv5ao.webp', description: 'Unleash your sewing potential with our Professional Quality Sewing Machine, a powerhouse tool designed for precision and efficiency. Packed with advanced features, this machine ensures seamless stitching for even the most intricate projects. Elevate your craftsmanship with this top-of-the-line sewing machine, making every stitch a masterpiece.', price: 249.99, inventory: 10 },
  { name: 'Paintbrush Duo', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387529/painting-brushes-duo-product_rhqnls.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387526/painting-brushes-duo-thumbnail_mdanqe.webp', description: 'Upgrade your painting experience with our Paintbrush Duo, a dynamic pair designed to elevate your artistic endeavors. Crafted with precision and versatility, these brushes offer optimal control for both broad strokes and intricate details. Whether you are a seasoned artist or just starting out, this duo is the perfect complement for creating captivating masterpieces.', price: 19.99, inventory: 100 },
  { name: 'Christmas Craft Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387490/diy-christmas-crafts-product_xvjhnc.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387488/diy-christmas-crafts-thumbnail_qtswth.webp', description: 'Transform your space into a festive wonderland with our Christmas Craft Kit, curated for holiday enthusiasts seeking a touch of DIY magic. This comprehensive kit includes everything needed to craft charming snowglobes, fabric Christmas trees, and festive window decor. Unleash your creativity and infuse your home with the spirit of the season as you handcraft these delightful holiday treasures.', price: 39.99, inventory: 24 },
  { name: 'Puff Paints', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387471/painting-puff-paints-set-product_zhpoie.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387473/painting-puff-paints-set-thumbnail_wempnb.webp', description: 'Add a vibrant touch to your creations with our Puff Paint Set, a collection of 10 vivid colors that bring your projects to life with texture and flair. Ideal for fabric, paper, and more, these puff paints offer a fun and easy way to add dimension to your artistic endeavors', price: 39.99, inventory: 27 },
  { name: 'Pastel Shimmer Paint Set', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387467/painting-paint-and-brush-kit-product_frvqi4.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387469/painting-paint-and-brush-kit-thumbnail_ehhzwd.webp', description: 'Elevate your artistic endeavors with our Pastel Shimmer Paint Set, a sophisticated palette featuring subtle, shimmery tones that add class and allure to your projects. This set, complemented by 7 assorted brushes of various sizes, allows you to explore the world of oil-based paints with ease. Create masterpieces with a touch of elegance as you indulge in the smooth and lustrous finish that our pastel shimmer paints bring to your art.', price: 49.99, inventory: 47 },
  { name: 'Ultimate Paint Brush Variety Pack', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387150/painting-assorted-brushes-product_v29ybb.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387379/painting-assorted-brushes-thumbnail_mb9zvg.webp', description: 'Unleash your creativity with our Ultimate Paint Brush Variety Pack, a comprehensive collection featuring every brush you will ever need for your artistic endeavors. This versatile set includes an array of brushes, from fine detail to broad strokes, ensuring you have the perfect tool for any painting project.', price: 49.99, inventory: 47 },
  { name: '200 Spool Thread Storage System', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387322/sewing-thread-storage-product_jlwown.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387324/sewing-thread-storage-thumbnail_p6gtdw.webp', description: 'Organize your thread collection effortlessly with our 200 Spool Thread Storage System, a must-have for avid crafters and sewing enthusiasts. This comprehensive storage solution ensures easy access and tidy arrangement for your extensive thread assortment. Keep your creative space neat and efficient as you focus on stitching your next masterpiece with the convenience of this spacious and versatile thread storage system.', price: 99.99, inventory: 4 },
  { name: 'Felt Pumpkin Pin Cushion', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387318/sewing-pumpkin-pin-cushion-product_btvkas.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387321/sewing-pumpkin-pin-cushion-thumbnail_r8evyi.webp', description: 'Sew in seasonal style with our Felt Pumpkin Pin Cushion, a charming and functional accessory for every sewing toolkit. This delightful pin cushion not only keeps your pins organized and within reach but also adds a touch of autumn charm to your crafting space. Crafted from soft and durable felt, this pumpkin pin cushion is a whimsical yet practical addition to your creative endeavors.', price: 9.99, inventory: 44 },
  { name: 'Top Quality Thread Assortment', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387315/sewing-thread-variety-pack-product_pttik3.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387317/sewing-thread-variety-pack-thumbnail_eqcexj.webp', description: 'Crafted for sewing enthusiasts, this assortment provides ample thread to sustain your passion for an extended period, ensuring you have the perfect shade for every stitching endeavor. Immerse yourself in the world of vibrant hues and superior quality threads, making it an essential addition to any sewing toolkit.', price: 49.99, inventory: 64 },
  { name: 'Extra Long Tape Measure', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387291/sewing-tape-measure-product_sxjmoz.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387286/sewing-tape-measure-thumbnail_aqxooh.webp', description: 'Meet your crafting needs with our Extra-Long Tape Measure, designed to provide convenience and precision for projects that require extended measurements. With an impressive length, this tape measure is an essential tool for sewing, knitting, quilting, and a variety of other crafts.', price: 7.99, inventory: 35 },
  { name: 'Pastel Pin Cushion', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387288/sewing-pin-cushion-product_iqr7sy.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387289/sewing-pin-cushion-thumbnail_yy2k5x.webp', description: 'Add a touch of whimsy to your crafting space with our Pastel Pin Cushion featuring adorable pom-poms and a crafty aesthetic. This charming pin cushion not only keeps your pins organized but also brings a delightful and playful vibe to your creative haven. Crafted with care and designed for both style and functionality, it is the perfect accessory for any crafting enthusiast.', price: 7.99, inventory: 25 },
  { name: 'Cross Stitch Frame & Fabric', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387260/crossstich-frame-and-cloth-product_pr6vfu.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387267/crossstich-frame-and-cloth-thumbnail_uuaide.webp', description: 'Unlock boundless creativity with our Cross Stitch Frame and Fabric set, a blank canvas inviting endless possibilities for crafters to weave their artistic tapestry. This versatile kit features a sturdy frame and high-quality fabric, providing the perfect foundation for your cross-stitching masterpieces.', price: 12.99, inventory: 15 },
  { name: 'Fabric Display & Storage Rack', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387155/sewing-fabric-storage-product_n95rro.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706387154/sewing-fabric-storage-thumbnail_h3jrtr.webp', description: 'Organize your creative space with our Fabric Display and Storage Rack, a spacious solution designed to accommodate up to 30 full bolts of fabric. This sturdy and practical rack not only showcases your vibrant fabric collection but also keeps it easily accessible for seamless crafting', price: 139.99, inventory: 15 },
  { name: 'Cross Stitch Thread 6 Pack', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377646/crossstich-thread-product_l0p4vg.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377645/crossstich-thread-thumbnail_hso9rn.webp', description: 'Explore the vibrant spectrum of creativity with our Cross Stitch Thread 6-Pack, featuring an array of dazzling rainbow colors. Perfect for adding a burst of vivid hues to your cross-stitch projects, this collection includes high-quality threads that bring life and vibrancy to every stitch.', price: 9.99, inventory: 0 },
  { name: 'Luxury Soap Making Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377645/diy-soap-making-product_lfjram.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377644/diy-soap-making-thumbnail_i4ye7k.webp', description: 'Indulge in the art of soap making with our Luxury Soap Making Kit, a premium collection that combines high-quality essential oils with a luxurious shea butter soap base. This comprehensive kit provides everything you need to create exquisite, fragrant soaps that pamper your skin and tantalize your senses.', price: 59.99, inventory: 9 },
  { name: 'Kids Beading Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377644/kids-beading-kit-product_ibgbz3.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377644/kids-beading-kit-thumbnail_agyblz.webp', description: 'Ignite the creativity of a young mind with our Kids Beading Kit, a vibrant collection of beads in all shapes and colors, accompanied by a convenient storage box with multiple divided sections. This engaging kit is perfect for young crafters to explore their artistic flair and create personalized jewelry. Watch as their imaginations come to life, stringing together colorful beads to make unique and delightful creations, all neatly organized in the included storage box.', price: 39.99, inventory: 19 },
  { name: 'Sewing Starter Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377644/sewing-starter-set-product_csqte0.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377643/sewing-starter-set-thumbnail_kgegxo.webp', description: 'Embark on your sewing journey with our Sewing Starter Set, elegantly presented in an exquisite decorative box. This carefully curated set includes essential sewing tools, threads, and accessories, ensuring a seamless start to your crafting endeavors. Elevate your sewing experience with this stylish and practical starter set, perfect for both beginners and seasoned enthusiasts alike.', price: 29.99, inventory: 13 },
  { name: 'Vintage Quilting Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377643/diy-quilting-kit-product_s6oqjb.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377642/diy-quilting-kit-thumbnail_tecekx.webp', description: 'Embark on a nostalgic quilting journey with our Vintage Quilting Kit, a timeless collection that encapsulates the charm of yesteryear. This kit offers all the supplies needed to craft a twin-sized quilt, featuring an assortment of vintage patterns that evoke a sense of classic elegance. Dive into the world of quilting with this curated set, perfect for creating a cherished heirloom that combines the artistry of the past with the creativity of the present.', price: 79.99, inventory: 18 },
  { name: 'Old School Macrame Kit', image_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377643/diy-macrame-kit-product_p9caht.webp', thumbnail_url: 'https://res.cloudinary.com/ddqsowzpj/image/upload/v1706377642/diy-macrame-kit-thumbnail_ithv1l.webp', description: 'Revisit the groovy era of the 70s with our Old School Macramé Kit, designed to transport you back in time while crafting stylish and retro home decor. This kit includes all the materials and instructions to create nostalgic macramé pieces that capture the essence of a bygone era. Immerse yourself in the art of knotting and weaving with this throwback kit, adding a touch of vintage flair to your modern space.', price: 29.99, inventory: 12 },
]
Product.create(products)

# Seed Orders
orders = [
  { customer_id: 1, order_date: Date.parse('2023-06-22'), shipped_date: Date.parse('2023-06-28'), subtotal_amount: 283.97, tax_amount: 14.20, total_amount: 298.17 },
  { customer_id: 4, order_date: Date.parse('2023-10-28'), shipped_date: Date.parse('2023-11-07'), subtotal_amount: 61.98, tax_amount: 3.10, total_amount: 65.08 },
  { customer_id: 5, order_date: Date.parse('2024-01-02'), shipped_date: Date.parse('2024-01-09'), subtotal_amount: 134.93, tax_amount: 6.75, total_amount: 141.68 },
]
Order.create(orders)

# Seed Orders_Products
order_products = [
  { order_id: 1, product_id: 1, product_quantity: 2 },
  { order_id: 1, product_id: 2, product_quantity: 1 },
  { order_id: 2, product_id: 15, product_quantity: 1 },
  { order_id: 2, product_id: 23, product_quantity: 1 },
  { order_id: 3, product_id: 6, product_quantity: 4 },
  { order_id: 3, product_id: 8, product_quantity: 1 },
]
OrdersProduct.create(order_products)

# Seed Promotions
promotions = [
  { name: '30% Off Knitting', percent_discount: 30.0, start_date: nil, end_date: nil },
  { name: 'Summer Sale', percent_discount: 15.0, start_date: Date.parse('2023-06-21'), end_date: Date.parse('2023-08-21') },
]
Promotion.create(promotions)

# Seed Products_Categories

products_categories = [
  { product_id: 1, category_id: 1 },
  { product_id: 2, category_id: 2 },
  { product_id: 3, category_id: 1 },
  { product_id: 4, category_id: 6 },
  { product_id: 5, category_id: 1 },
  { product_id: 6, category_id: 4 },
  { product_id: 7, category_id: 5 },
  { product_id: 8, category_id: 4 },
  { product_id: 9, category_id: 2 },
  { product_id: 10, category_id: 3 },
  { product_id: 11, category_id: 2 },
  { product_id: 12, category_id: 1 },
  { product_id: 13, category_id: 4 },
  { product_id: 14, category_id: 5 },
  { product_id: 15, category_id: 3 },
  { product_id: 16, category_id: 5 },
  { product_id: 17, category_id: 5 },
  { product_id: 18, category_id: 4 },
  { product_id: 19, category_id: 3 },
  { product_id: 20, category_id: 5 },
  { product_id: 21, category_id: 3 },
  { product_id: 22, category_id: 5 },
  { product_id: 23, category_id: 3 },
  { product_id: 24, category_id: 1 },
  { product_id: 25, category_id: 6 },
  { product_id: 26, category_id: 1 },
  { product_id: 27, category_id: 1 },
  { product_id: 28, category_id: 6 },
  { product_id: 29, category_id: 5 },
  { product_id: 30, category_id: 6 },
  { product_id: 31, category_id: 1 },
  { product_id: 32, category_id: 5 },
  { product_id: 33, category_id: 1 },
  { product_id: 34, category_id: 1 },
  { product_id: 35, category_id: 1 },
  { product_id: 36, category_id: 1 },
  { product_id: 37, category_id: 2 },
  { product_id: 38, category_id: 4 },
  { product_id: 39, category_id: 3 },
  { product_id: 40, category_id: 4 },
  { product_id: 41, category_id: 4 },
  { product_id: 42, category_id: 4 },
  { product_id: 43, category_id: 2 },
  { product_id: 44, category_id: 2 },
  { product_id: 45, category_id: 2 },
  { product_id: 46, category_id: 2 },
  { product_id: 47, category_id: 2 },
  { product_id: 48, category_id: 6 },
  { product_id: 49, category_id: 2 },
  { product_id: 50, category_id: 6 },
  { product_id: 51, category_id: 3 },
  { product_id: 52, category_id: 5 },
  { product_id: 53, category_id: 2 },
  { product_id: 54, category_id: 3 },
  { product_id: 55, category_id: 3 },
]
ProductsCategory.create(products_categories)

# Seed Promotions_Products
promotions_products = [
  { promotion_id: 1, product_id: 1 },
  { promotion_id: 1, product_id: 3 },
  { promotion_id: 1, product_id: 5 },
  { promotion_id: 1, product_id: 12 },
  { promotion_id: 1, product_id: 24 },
  { promotion_id: 1, product_id: 26 },
  { promotion_id: 1, product_id: 27 },
  { promotion_id: 1, product_id: 31 },
  { promotion_id: 1, product_id: 34 },
  { promotion_id: 1, product_id: 35 },
  { promotion_id: 1, product_id: 36 },
]
PromotionsProduct.create(promotions_products)